id: saraalert-fhir
canonical: http://saraalert.org
name: SaraAlert
status: active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: The MITRE Corporation
  url: http://www.mitre.org
dependencies:
  hl7.fhir.us.core: 3.1.0

menu:
  Home: index.html
  Artifacts: artifacts.html

parameters:
  apply-contact: true
  apply-jurisdiction: false
  apply-publisher: true